language: go
go:
  - 1.6.2
  - release
  - tip

before_install:
  - go get github.com/tools/godep

go_import_path: github.com/bjjyd

install:
  - godep restore

script:
  - cd cmd/shadowss/server && go build -a  -o shadowss
